server:
  port: 9191
#configure
spring:
  application:
    name: API-Gateway
  cloud:
    gateway:
      routes:
        - id: BOOK-SERVICE
          uri: lb://BOOK-SERVICE
          predicates:
            - Path=/books/**


#Configure
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      hostname: localhost